name: Deploy to Azure

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          pip install -r requirements.txt -r requirements-dashboard.txt pytest
      - name: Debug user length
        run: |
          echo "AZURE_WEBAPP_USER length: ${#AZURE_WEBAPP_USER}"  
          echo "First 5 chars: ${AZURE_WEBAPP_USER:0:5}"
          echo "AZURE_WEBAPP_USER: ${{ secrets.AZURE_WEBAPP_USER }}"
          echo '${{ secrets.AZURE_WEBAPP_USER }}'
        env:
          AZURE_WEBAPP_USER: ${{ secrets.AZURE_WEBAPP_USER}}
          AZURE_WEBAPP_PASS: ${{ secrets.AZURE_WEBAPP_PASS}}  
     # - name: Run tests
        #run: pytest tests/

  deploy-api:
   # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip
      - name: Install deps
        run: pip install -r requirements.txt
      - name: fix test
        run: pip install -e .  
      - name: Zip API
        run: zip -r api.zip api/ src/ requirements.txt
      - name: Deploy Function App via ZIP
        env:
              AZURE_FUNC_USER: ${{ secrets.AZURE_FUNC_USER }}
              AZURE_FUNC_PASS: ${{ secrets.AZURE_FUNC_PASS }}
        run: |
            zip -r api.zip api/ src/ host.json requirements.txt
            curl -v -X POST \
            -u "$AZURE_FUNC_USER:$AZURE_FUNC_PASS" \
            -H "Content-Type: application/zip" \
            --data-binary @api.zip \
            "https://czech-drivers-api-cfeqcadvc0cwfbhk.scm.germanywestcentral-01.azurewebsites.net/api/zipdeploy"
                    
  deploy-dashboard:
   # needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip
      - name: Install dashboard deps
        run: |
          cp requirements-dashboard.txt requirements.txt
          echo "=== requirements.txt content ==="
          cat requirements.txt
          echo "================================"
          pip install -r requirements.txt
      - name: Zip dashboard
        run: |
          cp requirements-dashboard.txt requirements.txt
          echo "=== requirements.txt content ==="
          cat requirements.txt
          echo "================================"
          zip -r dash.zip dashboard/ requirements.txt
      - name: Deploy to Azure App Service
        run: |
          curl -X POST \
            -u "${AZURE_WEBAPP_USER}:${AZURE_WEBAPP_PASS}" \
            -H "Content-Type: application/zip" \
            --data-binary @dash.zip \
            "https://czech-drivers-dashboard-fmdbcfahd4habvh4.scm.polandcentral-01.azurewebsites.net/api/zipdeploy" \
            -v  # ← verbose mode shows errors
        env:
          AZURE_WEBAPP_NAME: "czech-drivers-dashboard"
          AZURE_WEBAPP_USER: ${{ secrets.AZURE_WEBAPP_USER }}
          AZURE_WEBAPP_PASS: ${{ secrets.AZURE_WEBAPP_PASS }}
# "https://czech-drivers-dashboard-fmdbcfahd4habvh4.scm.polandcentral-01.azurewebsites.net:443/api/zipdeploy" \          



#run: |
#          curl -X POST \
#            -u "${AZURE_FUNC_USER}:${AZURE_FUNC_PASS}" \
#            -H "Content-Type: application/zip" \
#            --data-binary @api.zip \
#            "https://czech-drivers-api-cfeqcadvc0cwfbhk.scm.germanywestcentral-01.azurewebsites.net/api/zipdeploy" \
#            -v  # ← verbose mode shows errors
#        env:
#          AZURE_FUNCTION_NAME: "czech-drivers-api"
#          AZURE_FUNC_USER: ${{ secrets.AZURE_FUNC_USER }}
#          AZURE_FUNC_PASS: ${{ secrets.AZURE_FUNC_PASS }}
#          AZURE_FUNCTION_PUBLISH_PLAN: ${{ secrets.AZURE_FUNCTION_PUBLISH_PLAN }}